// SLAVE CODE
// This code configures the Arduino/AVR board as an SPI Slave.
// The slave waits for data from the SPI Master.
// When data is received, it prints the received value in the Serial Monitor.
// It also sends back the value 60 to the master.

#include <avr/io.h>      // Gives access to AVR registers like DDRB, SPCR, SPSR, SPDR
#include <Arduino.h>     // Allows us to use Arduino functions like Serial.begin() and Serial.println()

void SPI_SlaveInit() {
  // PB4 = MISO
  // MISO means Master In Slave Out.
  // The slave uses this pin to send data back to the master.
  // So, for the slave, MISO must be an output.
  DDRB |= (1 << PB4);

  // PB2 = SS
  // PB3 = MOSI
  // PB5 = SCK
  //
  // These pins are inputs for the slave:
  // SS tells the slave when it is selected.
  // MOSI brings data from the master to the slave.
  // SCK is the clock signal generated by the master.
  DDRB &= ~((1 << PB2) | (1 << PB3) | (1 << PB5));

  // Enable SPI.
  // Only SPE is set because this device is a slave by default.
  // We do not set MSTR, because MSTR would make it a master.
  SPCR = (1 << SPE);

  // Put 60 into the SPI Data Register.
  // This is the value that will be sent back to the master during SPI transfer.
  //
  // Important: SPI sends and receives at the same time.
  // So while the master sends one byte to the slave,
  // the slave also sends one byte back to the master.
  SPDR = 60;
}

void setup() {
  // Start serial communication so we can see received values in Serial Monitor.
  Serial.begin(9600);

  // Initialize this board as an SPI slave.
  SPI_SlaveInit();
}

void loop() {
  // Check if SPI transfer is complete.
  // SPIF means SPI Interrupt Flag.
  // It becomes 1 when one full byte has been received through SPI.
  if (SPSR & (1 << SPIF)) {

    // Read the received byte from SPDR.
    // The master sent this value to the slave.
    //
    // Reading SPDR after checking SPSR clears the SPIF flag.
    uint8_t received = SPDR;

    // Print the received value to the Serial Monitor.
    // For example, if the master sends 85, 170, 255,
    // those numbers will appear here one by one.
    Serial.println(received);

    // Load 60 again into SPDR.
    // This prepares the slave to send 60 back during the next SPI transfer.
    SPDR = 60;
  }
}
